import Head from "next/head";
import Image from "next/image";
import ArticleAndImage from "../core/components/ArticleAndImage/ArticleAndImage";
import DipatchImagesInChildren from "../core/components/DispatchImagesInChildren/DipatchImagesInChildren";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <DipatchImagesInChildren dir={["home/desktop/"]}>
          <ArticleAndImage style="black"></ArticleAndImage>
          <ArticleAndImage style="white--invert"></ArticleAndImage>
          <ArticleAndImage style="white"></ArticleAndImage>
        </DipatchImagesInChildren>
      </section>
    </div>
  );
}
