import Head from "next/head";
import Image from "next/image";
import DipatchImagesInChildren from "../core/components/DispatchImagesInChildren/DipatchImagesInChildren";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <DipatchImagesInChildren dir={[]}></DipatchImagesInChildren>
      </section>
    </div>
  );
}
